#!/bin/sh
### BEGIN INIT INFO
# Provides:          SmartPi2EmonCMS
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Kurze Beschreibung
# Description:       Längere Beschreibung
### END INIT INFO

# Actions
case "$1" in
    start)
        su pi -c /usr/local/bin/smartpi2emoncms.py &
        ;;
    stop)
        sudo pkill -f /usr/local/bin/smartpi2emoncms.py
        ;;
    restart)
        sudo pkill -f /usr/local/bin/smartpi2emoncms.py
        sleep 1
        su pi -c /usr/local/bin/smartpi2emoncms.py &
        ;;
esac

exit 0
